### ISSUE TITLE
The 25 clubs limit is far too low

### ISSUE THREAD

**Issue by anonymousmaggot** [duolicious/duolicious-frontend#315]
re: #312 
It's quite buggy, and wiped all my interests that only I had. I was taken below the 25 limit so I'm not sure what the point of this was. Tried to re-add the musician I really like that was removed and it appeared to not work, so I instead added a video game lots of others have. I refreshed, and somehow both were added so now I'm at 26/25.
I honestly don't see the point to this, you're just making it harder to find people we share interests with. Some people did just write random shit there but lots (including me) had only genuine interests. Sure, no one else had some of my clubs but what if someone who signs up in the future happens to like my obscure interests too? I think 50 or 100 would be better if it's absolutely necessary to have a limit.
Will you at least implement a way to filter/search by clubs?

**Comment by duogenesis** [comment]
Thanks for the bug report. It's true that the 25-club limit isn't properly being enforced. This is an issue with the backend which I'll fix in the coming few hours.

>I was taken below the 25 limit

This could have been because you were in a banned club. When the cut-off was enforced last night, people were removed from the least popular clubs such that they were in at most 25 clubs. _Then_, people were also removed from [this](https://github.com/duolicious/duolicious-backend/blob/d0d307cc7e2a56e8a42aa03ac6182c3c2eba74c1/banned-club.sql) list of banned clubs, which might have resulted in you being in less than 25 clubs. I welcome feedback on this list, because although the vast majority of entries on it clearly deserve to have been removed from Duolicious, it was made manually and might contain mistakes. Maybe I removed a musician whose name contained "suicide" or similar; there were a few musicians I noticed like that which I was careful not to ban, although it seems like I accidentally added some anyway.

>I'm not sure what the point of this was

Search performance. Some Duolicious members were part of over 600 clubs. Being part of many clubs slows down searching for other users. For each club, the search algorithm needs to check if it's shared with someone else. More clubs = more checks.

The search performance issue could have alternatively be addressed by not using clubs to reorder people's search results.

There might be other ways to address performance. I'd need to look into it. But there certainly needs to be _some_ limit on clubs to prevent abuse. I don't mind people writing "random shit". What I think of as abuse is slowing down searching for other users, potentially crashing others' apps when they visit profiles with long lists of clubs, or creating clubs that promote harm (e.g. "lithuainan suicide enjoyer", which is now banned).

>I think 50 or 100 would be better if it's absolutely necessary to have a limit.

50 clubs might be okay. I'd need to test performance. Even though the new club limit has only affected 5% of users who use clubs (and even fewer people who use Duolicious), I'll still consider increasing the limit.  I know that about 95% of people who used clubs at the time the cut-off was enforced were part of 25 clubs or less. About 99% of people who use clubs were in 50 clubs or less.
